flowchart TD

subgraph GitHub["GitHub Repos"]
    BE["cloudops-backend"]
    FE["cloudops-frontend"]
end

CI[GitHub Actions CI/CD] --> DH[DockerHub]

BE --> CI
FE --> CI

DH --> EC2[AWS EC2  Backend API]
DH --> S3CF[AWS S3 CloudFront Frontend]

EC2 --> MON[Prometheus + Grafana Monitoring]